language: node_js
node_js:
  - "8"
deploy:
  provider: npm
  email: info@compknowhow.com
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
notifications:
  email:
    recipients:
      - info@compknowhow.com
    on_success: change
    on_failure: always
